
<script src="<?php echo $this->getJsUrl() ?>magestore/coresuccess/menu.js"></script>
<script type="text/javascript">
    var erpMenu = new ERPmenuController('<?php echo $this->__('Hide Main Menu'); ?>', '<?php echo $this->__('Show Main Menu'); ?>');
</script>
<h3>
    <a href="javascript:void(0);" <?php if (!$this->isInDashboard()): ?>onclick="showDashboardMenu();"<?php endif; ?>>
        <span><!--i class="fa fa-th"></i--> <?php echo $this->getTitle() ?></span>
    </a>
</h3>    
<div id="show_main_menu">
    <a href="javascript:void(0);" onclick="erpMenu.showmainmenu()">
        <i class="fa fa-angle-double-down"></i>
    </a>
</div>
