<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Google Maps Multiple Markers</title>
	<script src="https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyAI6uwssW8t2bH8rx3EXLm8X4swjY3zanI" type="text/javascript"></script>
</head>
<body>
	<div id="map" style="width:100%;height:600px;"></div>
	<div id="result"></div>
  	<script type="text/javascript">

	    var map = new google.maps.Map(document.getElementById('map'), {
	      zoom: 8,
	      center: new google.maps.LatLng(29.3117, 47.4818),
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    });
	    var markers = [];
	    var infowindow = new google.maps.InfoWindow();

	    var marker, i;
	    function setMapOnAll(map) {
		  	for (var i = 0; i < markers.length; i++) {
		    	markers[i].setMap(map);
		  	}
		}
	    function addMarker(test, testing) {
		  	marker = new google.maps.Marker({
			    position: new google.maps.LatLng(test,testing),
			    map: map
		  	});
		  	markers.push(marker);
		}
		function clearMarkers() {
		  	setMapOnAll(null);
		}
		function deleteMarkers() {
		  	clearMarkers();
		  	markers = [];
		}
    	function ajaxRequest(){
    		jQuery.ajax({
				type: "JSON",
				url: "<?php echo Mage::helper('adminhtml')->getUrl('dirvermanagement/adminhtml_driverlocation/markerdisplay') ?>",
				data: {
					foo : "bar"
				},
				success: function(urlData) {
					var data = JSON.parse(urlData);
					var locations = [];
					jQuery.each( data, function( key, value ) {
						var temp = [];
						temp.push(value.name);
						temp.push(value.latitude);
						temp.push(value.longitude);
						temp.push(key);
						locations.push(temp);
					});
					deleteMarkers();
			      	for (i = 0; i < locations.length; i++) {
			      		addMarker(locations[i][1], locations[i][2]);
			     	 	google.maps.event.addListener(marker, 'click', (function(marker, i) {
					     	return function() {
						       	infowindow.setContent(locations[i][0]);
						       	infowindow.open(map, marker);
					     	}
				      	})(marker, i));
		    		}
			      	setTimeout(function(){var myajaxrequest=new ajaxRequest();}, 30000);
				}
			});
    	}
    	var myajaxrequest=new ajaxRequest();
    	</script>
</body>
</html>