<table class="table table-striped items" id="items">
    <thead>
    <tr>
        <td><?php echo Mage::helper('po_pdf')->__('Product Name')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Sku')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Price')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Qty')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Subtotal')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Discount Amount')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Row Total')?></td>
    </tr>
    </thead>
    <?php $_items = $this->getCreditmemo()->getAllItems(); ?>
    <?php foreach ($_items as $_item): ?>
        <?php if (!$_item->getOrderItem() || $_item->getOrderItem()->getParentItem()) continue; ?>
        <tbody>
        <?php echo $this->getItemHtml($_item) ?>
        </tbody>
    <?php endforeach; ?>
</table>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>prototype/prototype.js" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>varien/js.js" type="text/javascript"></script>
<script type="text/javascript">decorateTable('items', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>