<?php $shipment = $this->getShipment() ?>
<?php if ($shipment):?>
<table class="table table-striped items">
    <thead>
    <tr>
        <td><?php echo Mage::helper('po_pdf')->__('Shipped By')?></td>
        <td><?php echo Mage::helper('po_pdf')->__('Tracking Number')?></td>
    </tr>
    </thead>
    <?php foreach ($shipment->getAllTracks() as $_item): ?>
        <tbody>
            <tr>
                <td><?php echo $this->escapeHtml($_item->getTitle()) ?></td>
                <td><?php echo $this->escapeHtml($_item->getNumber()) ?></td>
            </tr>
        </tbody>
    <?php endforeach; ?>
</table>
<?php endif;?>