<style type="text/css">
    .arrival-info ul{ border:none !important; padding:0 !important; margin:0 !important;}
    .arrival-info li{ margin-bottom:10px; text-align:left; }
    .arrival-info label{ font-weight:bold; color:#666666;}
</style>
<form action="" id="checkout-agreements" onsubmit="return false;">  
    <div class="buttons-set arrival-info">
       
    </div>

    <?php if (!$this->getAgreements()) return; ?>

    <ol class="checkout-agreements">
        <?php foreach ($this->getAgreements() as $_a): ?>
            <li>
                <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                    <?php if ($_a->getIsHtml()):?>
                        <?php echo $_a->getContent() ?>
                        <?php else:?>
                        <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
                        <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->htmlEscape($_a->getCheckboxText()) ?></label>
                </p>
            </li>
            <?php endforeach ?>
    </ol>
</form>
<script type="text/javascript">

</script>