<?php
$admin_user_session = Mage::getSingleton('admin/session');
$adminuserId = $admin_user_session->getUser()->getUserId();
$role_data = Mage::getModel('admin/user')->load($adminuserId)->getRole();
$dispatch_user = Mage::getStoreConfig('customconfig_options/section_two/dispatch');
?>
<?php $_order = $this->getOrder() ?>
<div>
<div id="order-messages">
    <?php echo $this->getChildHtml('order_messages') ?>
</div>
<div class="clear"></div>
<div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
        </div>
</div>
<?php echo $this->getItemsHtml() ?>
<div class="clear"></div>
    
<?php echo $this->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>
<?php if ($_order->getIsVirtual()): ?>
    <div class="box-right">
        <?php else: ?>
        <div class="box-left">
            <?php endif; ?>
        <!--Payment Method-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <?php echo $this->getPaymentHtml() ?>
                <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="box-right">
            <!--Shipping Method-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
                </div>
                <fieldset>
                    <?php  if ($_order->getTracksCollection()->count()) : ?>
                        <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track Order') ?>"><?php echo $this->__('Track Order') ?></a>
                        <br/>
                        <?php endif; ?>
                    <?php if ($_order->getShippingDescription()): ?>
                        <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>

                        <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                            <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                            <?php else: ?>
                            <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                            <?php endif; ?>
                        <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        <?php else: ?>
                        <?php echo $this->helper('sales')->__('No shipping information available'); ?>
                        <?php endif; ?>
                </fieldset>
            </div>
        </div>
        <?php endif; ?>
        <div class="clear"></div>
        <?php $class = "box-left"; if($role_data->getRoleId() == $dispatch_user || $role_data->getRoleId() == 1){?>
            <div class="box-left">
                <div class="entry-edit">
                    <?php echo $this->getLayout()->createBlock('dirvermanagement/adminhtml_order_view_tab_driver')->setTemplate('ewall/dirvermanagement/order/view/tab/driver.phtml')->toHtml(); ?>
                </div>
            </div>
        <?php $class = "box-right";}?>
        <div class="<?php echo $class?>">
            <div class="entry-edit">
                <?php echo $this->getLayout()->createBlock('dirvermanagement/adminhtml_order_view_tab_status')->setTemplate('ewall/dirvermanagement/order/view/tab/status.phtml')->toHtml(); ?>
            </div>
        </div>
        <div class="clear"></div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Delivery Date Information') ?></h4>
            </div>
        </div>
        <div class="grid np">
        <?php if($role_data->getRoleId() != Mage::getStoreConfig('customconfig_options/section_two/pos_user')):?>
            <fieldset>
                <?php  
                   
                    if ($_order->getShippingArrivalDate()!='')
                        echo "<strong>Shipping Arrival Date : </strong>".$_order->getShippingArrivalDate();
                    else
                        echo "<strong>Shipping Arrival Date :- </strong> N/A";
                    if ($_order->getShippingArrivalComments()!='')
                        echo "<br/><strong>Comment : </strong>".$_order->getShippingArrivalComments();
                ?>
            </fieldset>
        <?php elseif($role_data->getRoleId() == Mage::getStoreConfig('customconfig_options/section_two/pos_user')):?>
            <fieldset>
            <?php 
                $currentDate = date('Y-m-d');
                $currenttime = '';
                if ($_order->getShippingArrivalDate()!=''){
                   if($_order->getShippingDeliveryDate()){
                        $date_only = explode(' ',$_order->getShippingDeliveryDate());
                        $currentDate = $date_only[0];
                        $currenttime = $_order->getShippingArrivalTimeSlot();
                    }
                } 
            ?>

            <form class="form status" enctype="multipart/form-data" action="<?php echo Mage::helper('adminhtml')->getUrl('dirvermanagement/adminhtml_driver/changedeliverydate',array('store'=>Mage::app()->getRequest()->getParam('store')));; ?>" 
            id="assign_status_form" method="post">
                <div><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /></div>
                <input name="order_id" type="hidden" value="<?php echo $_order->getId();?>" />
                <label class="normal" for="delivery_date" style="padding: 10px;"><?php echo $this->__('Shipping Arrival Date :')?></label>
                <img style="" title="Select Date" id="date_select_trig" alt="" src="<?php echo $this->getSkinUrl("images/grid-cal.gif");?> "/>
                <input type="text" name="delivery_date" id="delivery_date" value="<?php echo $currentDate; ?>"/>                
                <label class="normal" for="shipping_arrival_time" style="padding: 10px;"><?php echo $this->__('Shipping Arrival Time :')?>
                </label>       
                <select name="shipping_arrival_time">
                <?php if(count($mang = Mage::helper('deliverydate')->deliverytimegetdata())){ ?>
                <?php foreach ($mang as $data) {  ?>   
                    <option value="<?php echo $data->getData('id')?>" <?php echo ($data->getData('id') == $currenttime) ? 'selected':'';?>>
                        <?php echo $data->getData('fromtime')." - ".$data->getData('totime'); ?>
                    </option>         
                <?php } ?>
                <?php }else{?>
                    <option value="0"></option>  
                <?php }?> 
                </select>                 
                <span class="submit_date" style="float:right">
                   <input class="assign scalable save submit-button" type ="submit" value="Change Delivery Date" title="Change Delivery Date"/>
                </span>
                <script type="text/javascript">
                    // <![CDATA[
                    Calendar.setup({
                    inputField : 'delivery_date',
                    ifFormat : '%Y-%m-%d',
                    showsTime: true,
                    button : 'date_select_trig',
                    singleClick : true,
                    disableFunc: function(date) {
                    //disable previous day in datepicker
                    var now= new Date();
                    if(date.getFullYear()<now.getFullYear())
                    {
                    return true;
                    }
                    if(date.getFullYear()==now.getFullYear())
                    {
                    if(date.getMonth()<now.getMonth())
                    {
                    return true;
                    }
                    }
                    if(date.getMonth()==now.getMonth())
                    {
                    if(date.getDate()<now.getDate())
                    {
                    return true;
                    }
                    }
                    },
                    });
                    // ]]>
                </script>
            </form>
            </fieldset>
        <?php endif;?>
        </div>
    <?php echo $this->getGiftOptionsHtml() ?>
    <div class="clear"></div>

    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
            </div>
            <fieldset><?php echo $this->getChildHtml('order_history') ?></fieldset>
        </div>
    </div>
    <div class="box-right entry-edit">
        <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Order Totals') ?></h4></div>
        <div class="order-totals"><?php echo $this->getChildHtml('order_totals') ?></div>
    </div>
    <div class="clear"></div>
</div>

<?php echo $this->getChildHtml('popup_window');?>
<script type="text/javascript">
    //<![CDATA[
    /**
    * Retrieve gift options tooltip content
    */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0,30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    //]]>
</script>
