<div class="ms-webpos">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" style="display: none">
        <div class="loader">
        </div>
    </div>
    <div id="o-wrapper" class="o-wrapper  wrap-checkout-page" data-bind="scope:'webpos.container'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <nav id="c-menu--push-left" class="c-menu c-menu--push-left" data-bind="scope:'webpos.menu'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </nav>
    <div id="c-mask" class="c-mask"></div>
    <div id="webpos-main-overlay" class="pos-overlay main"></div>
    <div id="webpos-medium-overlay" class="pos-overlay medium"></div>
</div>

<div id='select_cash_drawer_popup' data-bind="scope:'webpos.tills'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<div id='webpos-notification' data-bind="scope:'webpos.notification'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script>
    require([
        'uiApp',
        'dataManager',
        'lib/jquery/posOverlay',
        'lib/jquery/posAlert',
        'lib/jquery/posPopup'
    ], function (app, DataManager) {

        /* fix js bootstrap conflict with prototype hiden element */
        if (Prototype.BrowserFeatures.ElementExtensions) {
            var disablePrototypeJS = function (method, pluginsToDisable) {
                    var handler = function (event) {
                        event.target[method] = undefined;
                        setTimeout(function () {
                            delete event.target[method];
                        }, 0);
                    };
                    pluginsToDisable.each(function (plugin) {
                        jQuery(window).on(method + '.bs.' + plugin, handler);
                    });
                },
                pluginsToDisable = ['collapse', 'dropdown', 'modal', 'tooltip', 'popover', 'tab'];
            disablePrototypeJS('show', pluginsToDisable);
            disablePrototypeJS('hide', pluginsToDisable);
        }
        /* end fix */

        DataManager.setData(<?php /* @escapeNotVerified */ echo Zend_Json::encode($this->getWebposData()); ?>);

        app({
            components: <?php echo Zend_Json::encode($this->getJsLayout('components'));?>
        });

    });
</script>
<?php if($color = $this->getWebposColor()):?>
    <style type="text/css">
        .list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus,
        .btn-open-shift.bg-cl-active,
        .number.bg-cl-active,
        .bg-cl-active.active,
        .bg-cl-active.selected, .btn-cl-cfg-active,
        #error-logs .nav > li > a:hover,
        #error-logs .nav-pills > li.active > a,
        #error-logs  .nav-pills > li.active > a:hover,
        #error-logs .nav-pills > li.active > a:focus,
        .sync_container .wrap-item-general .nav-pills > li.active > a,
        .sync_container .wrap-item-general .nav-pills > li.active > a:hover,
        .sync_container .wrap-item-general .nav-pills > li.active > a:focus,
        .modal-footer .action-accept
        {
            background: #<?php echo $color?> !important;
            border: 0 none!important;
            color: #fff;
        }
        .link-cl-cfg{color:#0873db !important}
    </style>
<?php endif?>

