<div class="ms-webpos">
    <div class="login-screen">
        <div class="wrap-login-form">
            <form class="form-login" role="form" id="webpos-login" method="post">
                <h1 class="title-page"><img src="<?php echo $this->getLogoUrl();?>" width="200px" height="200px" alt="logo"/></h1>
                <div class="input-box">
                    <select class="selectpicker form-control" id="select_store" name="select_store">
                        <?php
                        $stores = $this->getStores();
                        if(count($stores) > 0):
                            foreach ($stores as $store):
                        ?>
                        <option value="<?php echo $store['id']?>" <?php echo ($store['selected'])?'selected':''; ?>><?php echo $store['name']?></option>
                        <?php
                            endforeach;
                        endif;
                        ?>
                    </select>
                </div>
                <div class="form-group wrap-input">
                    <div class="input-box"><input type="text" class="form-control required-entry required" id="username" name="username" placeholder="Username"></div>
                    <div class="input-box"><input type="password" class="form-control required-entry required" id="pwd"
                           name="password" placeholder="Password"></div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default"><?php echo Mage::helper('webpos')->__('Login');?></button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    require(
        [
            'mage/url',
        ], function (url) {
            console.log('1');
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>');
        });
</script>

<script>
    require([
        'jquery',
        'login'
    ], function ($) {
        $('#webpos-login').webposLogin();
    })
</script>
<style>
    #select_store-button span.selectpicker{
        display: none;
    }
</style>